# Generated by Django 2.2.9 on 2020-11-15 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_memberbalance'),
        ('bookkeeping', '0016_auto_20181013_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=300, unique=True)),
                ('check_memo', models.BooleanField(default=True)),
                ('check_other', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookkeeping.Account')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
    ]
