# Generated by Django 2.2.9 on 2020-11-15 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0017_processingtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingtag',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookkeeping.Account'),
        ),
    ]
